<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 ./test.glb
-->
<script>
// @ts-nocheck

  import { Group } from 'three'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const { gltf } = useGltf('/test.glb')
</script>

<div>
  {#if $gltf}
  <T is={ref} {...$$restProps}>
    <T.Mesh geometry={$gltf.nodes.Cube.geometry} material={$gltf.materials.Material} />
    <T.Mesh
      geometry={$gltf.nodes.A2B2_Ville_MK1_v8.geometry}
      material={$gltf.nodes.A2B2_Ville_MK1_v8.material}
      position={[-80.39, 0, 0]}
    />

    <slot {ref} />
  </T>
{/if}

</div>
